version: 2.1

executors:
  worker:
    docker:
      - image: circleci/node
    working_directory: ~/ci

jobs:
  install:
    executor: worker
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
          - node_modules-
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

  test:
    executor: worker
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint
      - run:
          name: typecheck
          command: npm run typecheck

  build:
    executor: worker
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/ci
          paths: .

  publish:
    executor: worker
    steps:
      - attach_workspace:
          at: ~/ci
      - run:
          name: login
          command: npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
      - run:
          name: publish
          command: npm publish

workflows:
  version: 2
  ci:
    jobs:
      - install:
          filters:
              tags:
                only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
            - build
          context: npm token
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
